lab4/urls.py
from django.urls import path

from . import views

app_name = 'lab4'
urlpatterns = [
    path('', views.home, name = 'home'),
    path('register/', views.register, name = 'register'),
]

lab_1/urls.py
from django.urls import re_path
from .views import index
#url for app
urlpatterns = [
    re_path(r'^$', index, name='index'),
]

lab_2/urls.py
from django.urls import path
from .views import index

#url for app, add your URL Configuration

urlpatterns = [
#TODO Implement this
]

praktikum/urls.py
from django.conf.urls import include
from django.urls import re_path, path
from django.contrib import admin
from lab_1.views import index as index_lab1


urlpatterns = [
    re_path(r'^admin/', admin.site.urls),
    re_path(r'^lab-1/', include('lab_1.urls')),
    re_path(r'^lab-2/', include('lab_2.urls')),
    path('lab4/', include('lab4.urls')),
    path('', include('lab4.urls')),
]

lab4/models.py
from django.db import models

# Create your models here.

lab_1/models.py
from django.db import models

# Create your models here.

lab_2/models.py
from django.db import models

# Create your models here.

lab4/views.py
from django.shortcuts import render

my_name = 'Alfian Fuadi Rafli'

def home(request):
    response = {'name' : my_name}
    return render(request, 'home.html', response)

def register(request):
    response = {'name' : my_name}
    return render(request, 'register.html', response)

lab_1/views.py
from django.shortcuts import render
from datetime import datetime, date
# Enter your name here
mhs_name = 'Alfian Fuadi Rafli' # TODO Implement this
curr_year = int(datetime.now().strftime("%Y"))
birth_date = date(1999, 11, 17) #TODO Implement this, format (Year, Month, Date)
npm = 1706028650 # TODO Implement this
tempat_kuliah = 'Fasilkom UI'
hobi = 'Tenis Meja'
# Create your views here.
def index(request):
    response = {'name': mhs_name, 'age': calculate_age(birth_date.year), 'npm': npm, 'tk': tempat_kuliah, 'hobi': hobi}
    return render(request, 'index_lab1.html', response)

def calculate_age(birth_year):
    return curr_year - birth_year if birth_year <= curr_year else 0

lab_2/views.py
from django.shortcuts import render
from lab_1.views import mhs_name, birth_date

#TODO Implement
#Create a content paragraph for your landing page:
landing_page_content = ''

def index(request):
    response = {'name': mhs_name, 'content': landing_page_content}
    return render(request, 'index_lab2.html', response)

lab4/templates/home.html
{% load static %}
<html>
	<head>
		<!-- BOOSTRAP -->
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
		<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
		<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>
		
		<title>My First Project</title>
	</head>
	<body>
		{% include "nav.html" %}
		<div class = "container-fluid">
			<div class = "row">
				<div class = "col-4">
					<p style = "width : 100%; height : 3vw"></p>
					<div class = "row">
						<div class = "col-1"></div>
						<div class = "col-9">
							<img src = "{% static 'img/foto.jpg' %}" class = "img-fluid" alt = "Alfian Fuadi Rafli">
						</div>
					</div>
					
					<p style = "width : 100%; height : 2.7vw"></p>
					<div class = "row">
						<div class = "col-1"></div>
						<div class = "col-9">
							<a class="btn btn-primary btn-blocks btn-lg text-center" href = "https://drive.google.com/open?id=1urjl_SCXYwEWZyZgeNEgqi626AZD75l9" role="button" style = "width : 100%; font-size : 2vw; font-family : Consolas">UNDUH CV</a>
						</div>
					</div>
				</div>
				
				
				<div class = "col-8">
					<div class = "ml-1">
						<p style = "width : 100%; height : 2.5vw"></p>
						<p style = "font-size : 3vw; font-family : Consolas">ALFIAN FUADI RAFLI</p>
						<p style = "font-size : 2vw; font-family : Consolas">
							<br>Umur : 19
							<br>Alamat : Jl. Ambengan Batu II/31 Surabaya
							<br>No. Telefon : 082323779646
							<br>Email : alfianfuadi17@gmail.com
							<br>Website : alfianfuadi17.herokuapp.com
							<p style = "width : 100%; height : 5.8vw"></p>
							<div class = "row">
								<div class = "col-2"><a href = "https://web.facebook.com/alfian.fuady.9?_rdc=1&_rdr"><img src = "{% static 'img/fb.png' %}" alt = "Facebook" style = "width : 100%; height : 6vw"></a></div>
								<div class = "col-2"><a href = "https://twitter.com/alfianfuady"><img src = "{%static 'img/twitter.png'%}" alt = "Twitter" style = "width : 100%; height : 6vw"></a></div>
								<div class = "col-2"><a href = "#"><img src = "{%static 'img/in.png'%}" alt = "Linkedin" style = "width : 100%; height : 6vw"></a></div>
								<div class = "col-2"><a href = "https://plus.google.com/100444775065017737259"><img src = "{%static 'img/ig.png'%}" alt = "Instagram" style = "width : 100%; height : 6vw"></a></div>	
								<div class = "col-2"><a href = "https://www.instagram.com/alfianfuadi17/"><img src = "{%static 'img/g+.png'%}" alt = "Google Plus" style = "width : 100%; height : 6vw"></a></div>
							</div>
						</p>
					</div>
				</div>
			</div>
		</div>
	</body>
</html>		

lab4/templates/nav.html
{% load static %}
<nav class = "navbar navbar-expand-sm bg-light">
	<ul class="navbar-nav">
		<li class = "nav-item"> <div class = "ml-3"> <a style = "font-family : Consolas" class="nav-link text-body" href = "{% url 'lab4:home' %}">Beranda</a></div></li>
		<li class = "nav-item"> <div class = "ml-3"> <a style = "font-family : Consolas" class="nav-link text-body" href = "#">Pendidikan</a></div></li>
		<li class = "nav-item"> <div class = "ml-3"> <a style = "font-family : Consolas" class="nav-link text-body" href = "#">Kemampuan</a></div></li>
		<li class = "nav-item"> <div class = "ml-3"> <a style = "font-family : Consolas" class="nav-link text-body" href = "#">Pengalaman</a></div></li>
		<li class = "nav-item"> <div class = "ml-3"> <a style = "font-family : Consolas" class="nav-link text-body" href = "{% url 'lab4:register' %}">Register Akun</a></div></li>
	</ul>
</nav>

lab4/templates/register.html
{% load static %}
<html>
	<head>
		<!-- BOOSTRAP -->
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
		<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
		<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>
		
		<title>My First Project</title>
	</head>
	<body>
		{% include "nav.html" %}
		<br>
		<form>
			<div class="form-group" style = "margin-left : 20px">
				<label>Nama</label>
				<input type = "text" class="form-control">
			</div>

			<div class="form-group date" style = "margin-left : 20px">
				<label>Tanggal</label>
				<input type = "date" class="form-control">
			</div>
			
			<div class="form-group" style = "margin-left : 20px">
				<label>Email</label>
				<input type = "email" class="form-control">
			</div>
			
			<div class="form-group" style = "margin-left : 20px">
				<label>Username</label>
				<input type = "text" class="form-control">
			</div>
			
			<div class="form-group" style = "margin-left : 20px">
				<label>Password</label>
				<input type = "password" class="form-control">
			</div>
			
			<div class="form-group" style = "margin-left : 20px">
				<label>Konfirmasi Pasword</label>
				<input type = "password" class="form-control">
			</div>
			
			</br>
			<button type="submit" class="btn btn-primary" style = "margin-left : 20px">Submit</button>
		</form>
	</body>
</html>

lab_1/templates/index_lab1.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ name }}</title>
</head>
<body>
	<h1>PROFIL</h1>
	<img src = "https://drive.google.com/uc?id=1DvkPR8Yhj__-QDv7yhiA2L5xGxL0jtrE" height = "300" width = "250">
    <p>Nama : {{ name }} <br/> </p>
    <p>NPM : {{ npm }}</p>
	<p>Tempat Kuliah : {{ tk }}</p>
	<p>Hobi : {{ hobi }}</p>
    <p>Desc : Saya berumur {{ age }} tahun. Saya berasal dari Surabaya.</p>
</body>
</html>

lab_2/templates/description_lab2addon.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>My Biodata</title>
</head>
<style>
    table, th, td {
        border: 1px solid black;
    }
    .subject{
        font-size: 20px;
        font-family: "Comic Sans MS";
        color: #6650ff;
    }
    .value{
        font-size: 20px;
        font-family: "Roboto", "Lucida Grande", Verdana, Arial, sans-serif;
        color: #ff102c;
    }
</style>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<body style="background-color: aqua">
    <h3 style="text-align: center">Hi all, This is my complete biodata</h3>
    <table align="center" style="text-align: center">
        {% for bio in bio_dict %}
            <tr>
                <td class="subject">{{ bio.subject }}</td>
                <td class="value">{{ bio.value }}</td>
            </tr>
        {% endfor %}
    </table>
    <br><br>
</body>

</html>

lab_2/templates/index_lab2.html
{% extends "base.html" %}
{% block content %}
<style>
    .center_screen {
        position: absolute;
        width: 500px;
        height: 50px;
        top: 50%;
        left: 50%;
        margin-left: -250px; /* margin is -0.5 * dimension */
        margin-top: -25px;
    }
</style>
<div class="center_screen">
    <p class="status" id="test">Hello, this is {{ name }}. {{ content }}.</p>
</div>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>My Biodata</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">
</head>
<style>
    table, th, td {
        border: 1px solid black;
    }
    .subject{
        font-size: 20px;
        font-family: "Comic Sans MS";
        color: #6650ff;
    }
    .value{
        font-size: 20px;
        font-family: "Roboto", "Lucida Grande", Verdana, Arial, sans-serif;
        color: #ff102c;
    }
</style>
<body style="background-color: lightgray">
    <div class="container-fullwidth">
        <nav class="navbar navbar-default navbar-expand-lg navbar-light bg-light">
          <a class="navbar-brand" href="#">Navbar</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
              <li class="nav-item">
                <a class="nav-link" href="/lab-2/">Home</a>
              </li>
              <li class="nav-item" >
                <a class="nav-link" href="/lab-2-addon/">About</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="/lab-3/">Diary</a>
              </li>
            </ul>
          </div>
        </nav>
    </div>
    {% block content %}
    {% endblock %}
</body>
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>
{% block jquery %}
{% endblock %}
</html>

templates/description_lab2addon.html
{% extends "base.html" %}
{% block content %}
<h3 style="text-align: center">Hi all, This is my complete biodata</h3>
<table align="center" style="text-align: center">
    {% for bio in bio_dict %}
        <tr>
            <td class="subject">{{ bio.subject }}</td>
            <td class="value">{{ bio.value }}</td>
        </tr>
    {% endfor %}
</table>
<br><br>
{% endblock %}

templates/to_do_list.html
{% extends "base.html" %}
{% block content %}
<h3 style="text-align: center">Hai semua, berikut adalah Catatan Harianku</h3>
<br><br>
<div class="row">
    <div class="col-md-6 col-xs-6">
        <table align="center" style="text-align: center">
            <tr>
                <th>Tanggal</th>
                <th>Yang akan dikerjakan</th>
            </tr>
            {% for diary_data in diary_dict %}
                <tr>
                    <td class="date">{{ diary_data.date }}</td>
                    <td class="activity">{{ diary_data.activity }}</td>
                </tr>
            {% endfor %}
        </table>
    </div>
    <div class="col-md-6 col-xs-6">
        <form method="POST" action="add_activity/">
            {% csrf_token %}
            <table>
                <tr>
                    <td>
                        Tanggal
                    </td>
                    <td>
                        <input type="datetime-local" name="date" id="date" required="required"/>
                    </td>
                </tr>
                <tr>
                    <td>
                        Kegiatan
                    </td>
                    <td>
                        <input type="text" name="activity" id="activity" size="25"/>
                    </td>
                </tr>
            </table>
            <button type="submit" class="button btn-success">Submit</button>
        </form>
    </div>
</div>
{% endblock %}